# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'codecanyon_mypets' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for codecanyon_mypets
pod 'TinyConstraints', '~> 4.0'

end
